name: Deploy Flask App to EC2

on:
  push:
    branches:
      - staging
  release:
    types: [created]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pip install pytest
          pytest test_app.py
          
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update -y
            sudo apt install -y git python3 python3-pip python3-venv tmux
          
            REPO_DIR="/home/ubuntu/my-flask-app"
            REPO_URL="https://github.com/ankitanand200193/github_action_May.git"
            VENV_DIR="$REPO_DIR/venv"
            
            # Set branch based on GitHub Actions environment variables
            if [ "$GITHUB_EVENT_NAME" == "release" ]; then
              BRANCH="main"
            elif [ "$GITHUB_EVENT_NAME" == "push" ] && [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
              BRANCH="staging"
            else
              echo "This script only runs for release events or pushes to the staging branch."
              exit 1
            fi
            
            # Clone or pull
            if [ -d "$REPO_DIR/.git" ]; then
              cd $REPO_DIR
              git checkout $BRANCH
              git pull origin $BRANCH
            else
              git clone --branch $BRANCH $REPO_URL $REPO_DIR
              cd $REPO_DIR
            fi

            
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            
            # Setup venv
            if [ ! -d "$VENV_DIR" ]; then
              python3 -m venv $VENV_DIR
            fi
          
            source $VENV_DIR/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          
            # Kill old process and start new one in tmux
            tmux kill-session -t flaskapp || true
            tmux new-session -d -s flaskapp "$VENV_DIR/bin/python app.py"
          
                      
                
                
                
                      
