name: Deploy Flask App to EC2

on:
  push:
    branches:
      - staging
  release:
    types: [created]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variable for MongoDB
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          pip install pytest
          pytest test_app.py
          
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update && sudo apt install -y git python3 python3-venv
            cd ~/my-flask-app || (git clone https://github.com/ankitanand200193/github_action_May.git ~/my-flask-app && cd ~/my-flask-app)
            git pull origin staging
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pkill -f "venv/bin/python3 app.py" || true
            echo "Starting Flask app with MONGO_URI in background"
            nohup bash -c "cd ~/my-flask-app && MONGO_URI='${{ secrets.MONGO_URI }}' venv/bin/python3 app.py" > flask.log 2>&1 &
      
      
      
      
            
